(:id "immortal-coil/base"
 :name "Immortal Coil"
 :version "0.0.1"
 :description "Bundled story graph."
 :depends-on ()
 :scripts ("sys/reboot.lisp"
           "maze/minigame.lisp"
           "maze/audio.lisp"
           "maze/rendering.lisp"
           "flight/minigame.lisp"
           "flight/rendering.lisp"
           "rogue/reveal.lisp"
           "rogue/delve/core.lisp"
           "rogue/delve/rendering.lisp"
           "war/radio.lisp"
           "war/audit.lisp"
           "forest/hide.lisp"
           "jrpg/state.lisp"
           "jrpg/tiles.lisp"
           "jrpg/rpg.lisp"
           "jrpg/combat.lisp"
           "jrpg/overworld.lisp"
           "jrpg/city.lisp"
           "jrpg/reveal.lisp"
           "jrpg/rites.lisp"
           "jrpg/character.lisp"
           "jrpg/shop.lisp"
           "opening.lisp"
           "campaign/forest.lisp"
           "campaign/jrpg.lisp"
           "campaign/carcosa.lisp"
           "campaign/dream-worlds.lisp"
           "campaign/war.lisp"
           "campaign/containment.lisp"
           "campaign/husk.lisp"
           "campaign/mutiny.lisp"
           "campaign/district.lisp"
           "campaign/tribunal.lisp"
           "campaign/house.lisp"
           "campaign/winter.lisp"
           "campaign/kept.lisp"
           "campaign/seam.lisp"
           "campaign/below.lisp"
           "campaign/lightsout.lisp"
           "campaign/nightshift.lisp"
           "campaign/release.lisp"
           "campaign/armistice.lisp"
           "editor-drafts.lisp")
 :assets "../assets/"
 :start "base/awake")
